---
title: "Inbreeding and Coancestry Coefficient Estimators"
author: "Seth Temple"
date: "November 10, 2019"
output:
  pdf_document: default
  html_document: default
---

```{r}
library(OmicKriging)
```

```{r}
source('vcf4popgen.R')
source('inbr&knshp_est.R')
source('beta_dosage.R') # https://github.com/jgx65/hierfstat/blob/master/R/beta_dosage.R
```

```{r}
data <- vcf_preproc('H2/chr22_jpt/chr22_jpt.vcf')
```

```{r}
minor_dosage <- data$d0
major_dosage <- data$d1
allele_freq <- data$p[,2]
```

Runtime experiment for inbr&knshp_est.R
```{r}
start <- Sys.time()
BETAS <- fBETA(minor_dosage, major_dosage)
end <- Sys.time()
print(end - start)
```

Runtime experiment for beta_dosage.R
```{r}
start <- Sys.time()
betas <- beta.dosage(t(minor_dosage))
end <- Sys.time()
print(end - start)
```

Accuracy check
```{r}
BETAS <- round(BETAS, 4)
betas <- round(betas, 4)
mean(BETAS == betas)
```

```{r}
gcta_inbr <- fGCTA(major_dosage, allele_freq)
gcta_kin <- kGCTA(major_dosage, allele_freq)
gcta_grm <- gcta_kin + diag(gcta_inbr)
```

Accuracy check
```{r}
GRM <- read_GRMBin('~/UW/Student/STAT 551/H/H2/chr22_jpt/chr22_jpt.grm')
GRM <- GRM - diag(diag(GRM))
GRM[1:5,1:5] - gcta_kin[1:5,1:5]
```

Accuracy check
```{r}
custom_hom <- fhom(data$a1, data$a2, allele_freq)
plink_hom <- read.table('~/UW/Student/STAT 551/H/H2/chr22_jpt/chr22_jpt.het',
                        header = TRUE)$F
mean(custom_hom - plink_hom) # rounding error
```

